const $=s=>document.querySelector(s);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const app=$('#app');
let config={catalog:[]},session=null,state=null,source=null,lastMessage=0,signature='',offset=0,recovering=false,retryAt=0,draft=null,answerDraft='',answerTurn=-1,busy=false,lastEvent=null,lastBeat=-1,audio=null,sound=false;
const storage={get(k){try{return sessionStorage.getItem(k);}catch{return null;}},set(k,v){try{sessionStorage.setItem(k,v);}catch{}},remove(k){try{sessionStorage.removeItem(k);}catch{}}};
try{session=JSON.parse(storage.get('categories.session'));}catch{}
let name=storage.get('categories.name')||'';
const invite=new URLSearchParams(location.search).get('room')?.toUpperCase()||'';
if(session&&invite&&session.room!==invite){session=null;storage.remove('categories.session');}
function toast(message){$('#toast').textContent=message;$('#toast').classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('#toast').classList.remove('show'),4200);}
async function api(action,data={}){
  const response=await fetch('./api',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...session,...data,action}),signal:AbortSignal.timeout(12000)});
  let result;try{result=await response.json();}catch{throw Error('The server is unavailable. Trying to reconnect.');}
  if(!response.ok){const e=Error(result.error||'Please try again.');e.expired=response.status===410;throw e;}return result;
}
function beep(frequency=600,duration=.08){if(!sound)return;try{audio??=new AudioContext();if(audio.state==='suspended')audio.resume();const oscillator=audio.createOscillator(),gain=audio.createGain();oscillator.connect(gain);gain.connect(audio.destination);oscillator.frequency.value=frequency;gain.gain.setValueAtTime(.04,audio.currentTime);gain.gain.exponentialRampToValueAtTime(.001,audio.currentTime+duration);oscillator.start();oscillator.stop(audio.currentTime+duration);}catch{}}
$('#sound').onclick=()=>{sound=!sound;$('#sound').innerHTML=`♫ <span>Sound ${sound?'on':'off'}</span>`;$('#sound').setAttribute('aria-pressed',String(sound));$('#sound').setAttribute('aria-label',sound?'Mute sound':'Enable sound');beep();};
$('#help').onclick=()=>$('#rules').showModal();document.querySelectorAll('.dialog-close').forEach(b=>b.onclick=()=>$('#rules').close());
const option=(value,label,selected)=>`<option value="${esc(value)}" ${value===selected?'selected':''}>${esc(label)}</option>`;
function landing(){
  $('#connection').textContent='Made for your people';
  app.innerHTML=`<section class="landing"><div class="intro"><div class="eyebrow"><span class="live-dot"></span> THE QUICK-THINKING PARTY GAME</div><h1>One category.<br>No repeats.<br><span>Zero chill.</span><svg viewBox="0 0 440 28" aria-hidden="true"><path d="M8 19 Q200 -7 431 13 M38 26 Q260 10 396 23"/></svg></h1><p class="intro-copy">A battle of brains, blank minds, and<br class="desktop"> “I was literally about to say that.”</p><div class="hero-tags"><span>✦ 2–12 friends</span><span>↗ No downloads</span><span>⏱ Instant pressure</span></div><div class="sample-board" aria-hidden="true"><div class="sample-label">NAME SOMETHING…</div><div class="sample-category">Fast food restaurants <span>🍟</span></div><div class="sample-answers"><span>McDonald’s <b>✓</b></span><span>Taco Bell <b>✓</b></span><span class="sample-you">Your turn… <b>08</b></span></div><div class="sticker">brain<br>buffering…</div></div></div><div class="entry-column"><section class="entry-card"><div class="card-topline"><span class="tiny-star">✳</span><span>GOOD TIMES START HERE</span><span>01 / GO</span></div><h2>Bring your<br>thinking cap.</h2><p>Your friends supply the chaos.</p><form id="entry-form"><label for="name">WHAT SHOULD WE CALL YOU?</label><input id="name" name="name" autocomplete="nickname" maxlength="20" placeholder="Your nickname" value="${esc(name)}" required><button class="button primary" type="submit" name="intent" value="create">Create a room <span>↗</span></button><div class="or"><span></span>OR JOIN THE PARTY<span></span></div><label for="room-code">GOT AN INVITE?</label><div class="join-row"><input id="room-code" name="room" maxlength="5" autocomplete="off" placeholder="ROOM CODE" value="${esc(invite)}" aria-label="Room code"><button class="button dark" type="submit" name="intent" value="join">Join →</button></div></form><div class="private-note"><span>⌑</span> Private rooms. Just you and your crew.</div></section><div class="mini-note"><span>↳</span><p>No accounts, no awkward introductions.<br>Just send the link and start playing.</p></div></div></section><section class="how-strip"><div><span>01</span><p><b>Get a category.</b><small>Animals? Brands? Things that are cold?</small></p></div><div><span>02</span><p><b>Keep it going.</b><small>Take turns. Beat the clock. No repeats.</small></p></div><div><span>03</span><p><b>Be the last one in.</b><small>One survivor. One point. Go again.</small></p></div></section>`;
  $('#entry-form').onsubmit=async e=>{e.preventDefault();if(busy)return;const action=e.submitter?.value||'create';name=$('#name').value.trim();const room=$('#room-code').value.trim().toUpperCase();if(!name)return toast('Choose a nickname first.');if(action==='join'&&!room)return toast('Enter your friend’s room code.');busy=true;e.submitter?.setAttribute('disabled','');try{session=await api(action,{name,room});storage.set('categories.session',JSON.stringify(session));storage.set('categories.name',name);history.replaceState(null,'',`?room=${session.room}`);connect();}catch(error){toast(error.message);e.submitter?.removeAttribute('disabled');}finally{busy=false;}};
}
function connect(){source?.close();lastMessage=Date.now();$('#connection').textContent='Connecting…';source=new EventSource(`./events?room=${encodeURIComponent(session.room)}&token=${encodeURIComponent(session.token)}`);source.addEventListener('state',e=>{lastMessage=Date.now();retryAt=0;$('#connection').textContent='● Live with your crew';const next=JSON.parse(e.data);offset=next.serverNow-Date.now();if(answerTurn!==next.turn){answerDraft='';answerTurn=next.turn;lastBeat=-1;}if(next.phase==='lobby'&&(state?.phase!=='lobby'||next.host!==state?.host))draft=null;state=next;const {serverNow,...stable}=next;const key=JSON.stringify(stable);if(key!==signature){signature=key;render();}if(next.event?.id!==lastEvent){lastEvent=next.event?.id;if(next.event)beep(next.event.kind==='out'?180:next.event.kind==='win'?880:660,.16);}});source.onerror=()=>{$('#connection').textContent='Reconnecting…';};}
async function recover(){if(!session||recovering||Date.now()<retryAt)return;recovering=true;try{await api('resume');connect();}catch(error){if(error.expired){source?.close();session=null;state=null;signature='';storage.remove('categories.session');landing();toast(error.message);}else{retryAt=Date.now()+4000;$('#connection').textContent='Offline · retrying…';}}finally{recovering=false;}}
const avatar=p=>`<span class="avatar color-${p.color}">${esc(p.name.slice(0,1).toUpperCase())}</span>`;
function players(){return `<aside class="players panel"><div class="section-heading"><h3>The crew</h3><span>${state.players.filter(p=>!p.left).length}/12</span></div><div class="player-list">${state.players.map(p=>`<div class="player ${p.id===state.active?'active':''} ${!p.alive&&state.phase!=='lobby'?'eliminated':''} ${p.left?'departed':''}">${avatar(p)}<div class="player-name"><b>${esc(p.name)} ${p.id===state.you?'<small>(you)</small>':''}</b><small>${p.left?'Left the room':!p.online?'Reconnecting…':state.phase==='lobby'?(p.id===state.host?'★ Host':'Ready to play'):p.id===state.active?'Thinking fast…':p.alive?'Still in':p.reason||'Watching · in next round'}</small></div><span class="score">${p.score}<small>pts</small></span></div>`).join('')}</div><div class="crew-note">${state.phase==='lobby'?'Everyone plays on their own device. Same room, same chaos.':'Out this round? Stay for the drama. You’re back in next round.'}</div></aside>`;}
function settings(){
  const host=state.host===state.you,s=host?(draft||state.settings):state.settings;
  const selected=config.catalog.find(c=>c.id===s.category);
  const note=s.pack==='Custom'?'Your categories are open: real answers count by default.':selected?selected.validation==='Dataset'?'Checked against '+selected.answerCount.toLocaleString()+' bundled answers and their aliases.':'Open category: unknown answers count by default.':'Bundled answer sets for listed categories. Open categories accept unknown answers.';
  return `<section class="settings panel"><div class="section-heading"><h3>Set the vibe</h3><span>${host?'YOU?RE THE HOST':'HOST SETTINGS'}</span></div>
  <form id="settings-form"><fieldset ${host?'':'disabled'}><div class="settings-grid">
  <label>Rounds<select name="rounds">${[1,3,5,7,10,15,20].map(n=>option(String(n),n+' round'+(n===1?'':'s'),String(s.rounds))).join('')}</select></label>
  <label>Time per turn<select name="seconds">${[4,6,8,10,15,20,30].map(n=>option(String(n),n+' seconds',String(s.seconds))).join('')}</select></label>
  <label>Category pack<select name="pack">${['All','Everyday','World','Culture','Local','Custom'].map(n=>option(n,n==='All'?'A bit of everything':n==='Local'?'Local ? your people':n,s.pack)).join('')}</select></label>
  <label>Category<select name="category" ${s.pack==='Custom'?'disabled':''}>${option('random','Surprise me',s.category)}${config.catalog.filter(c=>s.pack==='All'?c.pack!=='Local':c.pack===s.pack).map(c=>option(c.id,c.name,s.category)).join('')}</select></label>
  <label>Game mode<select name="mode">${option('normal','? Classic countdown',s.mode)}${option('rhythm','? Concentration ? 120 BPM',s.mode)}</select></label>
  <div class="judge-summary"><b>Dataset first. Friends settle it.</b><small>Instant checks. No setup needed.</small></div></div>
  <label class="custom-label ${s.pack==='Custom'?'':'hidden'}">Your custom categories <small>One per line</small><textarea name="custom" rows="3" maxlength="1000" placeholder="Teachers at our school&#10;Things that are annoying">${esc(s.custom)}</textarea></label>
  <label class="toggle-row"><span><b>Show previous answers</b><small>Switch off for a real memory test.</small></span><input name="showAnswers" type="checkbox" role="switch" ${s.showAnswers?'checked':''}></label>
  </fieldset><p class="judge-note">? ${esc(note)}</p><div class="callout-explainer"><b>Something doesn?t fit? Call Out.</b><p>With 3+ players still in, one other player must confirm. With 2, your opponent?s call-out stands immediately. The caller can briefly undo a slip.</p></div>
  ${host?`<div class="start-row"><button type="submit" class="button secondary" value="save">Save settings</button><button type="submit" class="button primary" value="start" ${state.players.filter(p=>!p.left).length<2?'disabled':''}>Let?s play <span>?</span></button></div><p class="start-note">${state.players.filter(p=>!p.left).length<2?'Invite one more person to get started.':'Starting saves your settings. Everyone ready?'}</p>`:'<div class="waiting">Waiting for the host to start<span>???</span></div>'}</form></section>`;
}
function board(){
  const s=state,me=s.players.find(p=>p.id===s.you),active=s.players.find(p=>p.id===s.active),mine=s.active===s.you,category=s.category;
  if(s.phase==='result'||s.phase==='finished')return results();
  let body='';
  if(s.phase==='reveal')body=`<div class="reveal-card"><span class="eyebrow">ROUND ${s.round} ? HERE WE GO</span><div class="reveal-icon">${category.icon}</div><h2>${esc(category.name)}</h2><p>A fresh category. Everybody?s back in.</p><div class="ready-count" data-countdown></div></div>`;
  else{
    const pending=s.pending,caller=s.players.find(p=>p.id===pending?.caller),confirmer=s.players.find(p=>p.id===pending?.confirmedBy);
    const heading=s.phase==='turn'?(mine?'? YOUR TURN':esc(active?.name)+' is answering?'):s.phase==='callout'?'? '+esc(caller?.name)+' CALLED IT OUT':s.phase==='calledout'?'? CALLED OUT':'? THAT COUNTS!';
    const reason=s.phase==='callout'?'One other player still in must agree. Otherwise, the answer counts.':s.phase==='calledout'?(confirmer?'Confirmed by '+confirmer.name+'. '+active?.name+' is out.':'Two players remain: the opponent?s call-out stands.'):pending?.reason;
    body=`<div class="category-heading"><span class="eyebrow">NAME SOMETHING IN?</span><h2><span>${category.icon}</span> ${esc(category.name)}</h2><span class="category-level">${esc(category.difficulty)} ? ${category.closed?'Dataset':'Open category'}</span></div><div class="turn-zone ${mine?'your-turn':''}"><div class="turn-label">${heading}</div>
      ${s.phase==='turn'?`<div class="timer" data-countdown></div><div class="timer-track"><div id="timer-fill"></div></div>${s.settings.mode==='rhythm'?'<div class="beats" aria-label="Four beat rhythm"><i></i><i></i><i></i><i></i></div><p class="beat-caption">Keep the rhythm ? answer before the beats run out</p>':''}`: `<div class="answer-reveal ${s.phase==='calledout'?'invalid-answer':''}">?${esc(pending?.answer)}?</div><p class="verdict-reason">${esc(reason)}</p><small class="review-clock"><span data-countdown></span>s ${s.phase==='review'?'to Call Out':s.phase==='callout'?'for one confirmation':'until play continues'}</small>`}
      ${s.phase==='turn'&&mine?`<form id="answer-form"><label class="sr-only" for="answer">Your answer</label><div class="answer-row"><input id="answer" autocomplete="off" maxlength="80" placeholder="Quick, name one?" value="${esc(answerDraft)}" required><button class="button primary" type="submit">Send ?</button></div><p>Press Enter to send. Make it count.</p></form>`:s.phase==='turn'?`<div class="spectator-message">${me.alive?'You?re still in. Keep an answer ready.':'You?re watching this round. Back in the next one.'}</div>`:''}
      <div class="callout-actions">${pending?.canCallOut?'<button class="button secondary" id="callout">? Call Out</button>':''}${pending?.canConfirm?'<button class="button danger" id="confirm-callout">Agree ? doesn?t fit</button>':''}${pending?.canUndo?'<button class="button secondary" id="cancel-callout">Undo my call-out</button>':''}</div>
      ${s.phase==='callout'&&!pending?.canConfirm?`<p class="callout-hint">${pending?.player===s.you?'Another active player must confirm.':pending?.caller===s.you?'Waiting for one other player to agree?':'You?re watching this call-out.'}</p>`:''}
    </div>`;
  }
  return `<section class="game-board panel">${body}</section><section class="answer-history panel"><div class="section-heading"><h3>${s.settings.showAnswers?'Already said':'Memory mode'}</h3><span>${s.answerCount} ACCEPTED</span></div>${s.settings.showAnswers?`<div class="answer-chips">${s.answers.length?s.answers.map((a,i)=>`<span class="${a.status==='invalid'?'invalid-answer':''}"><small>${String(i+1).padStart(2,'0')}</small> ${esc(a.answer)} <em>${a.status==='invalid'?'Called out ? ':''}${esc(a.name)}</em></span>`).join(''):'<p class="empty-note">A clean slate. The first answer is up for grabs.</p>'}</div>`:'<p class="memory-note">? Keep them in your head. Previous answers are hidden, but repeats still knock you out.</p>'}</section>`;
}
function results(){
  const finished=state.phase==='finished',sorted=[...state.players].sort((a,b)=>b.score-a.score),leaders=sorted.filter(p=>p.score===sorted[0].score),winner=state.players.find(p=>p.id===state.winner);
  return `<section class="result-board panel"><div class="confetti" aria-hidden="true">✦ <span>✳</span> · <span>✷</span> ✦</div><span class="eyebrow">${finished?'THAT’S A WRAP':`ROUND ${state.round} IN THE BOOKS`}</span><div class="trophy">${finished?'🏆':'👑'}</div><h2>${finished?(leaders.length>1?'A shared crown!':`${esc(leaders[0].name)} wins!`):(winner?`${esc(winner.name)} takes it!`:'A round of chaos.')}</h2><p>${finished?(leaders.length>1?leaders.map(p=>esc(p.name)).join(' & ')+' finish tied.':esc(state.event?.text)):(winner?'Last one standing. One point richer.':'No point awarded this round.')}</p><div class="leaderboard">${sorted.map((p,i)=>`<div class="leader-row"><span class="rank">${i&&p.score===sorted[i-1].score?sorted.findIndex(q=>q.score===p.score)+1:i+1}</span>${avatar(p)}<b>${esc(p.name)}${p.id===state.you?' (you)':''}${p.left?' · left':''}</b><strong>${p.score}<small>pts</small></strong></div>`).join('')}</div>${finished?(state.host===state.you?'<button class="button primary" id="lobby">Play again · back to lobby ↗</button><p class="start-note">Same crew. Fresh game. Change settings in the lobby.</p>':'<p>Waiting for the host to bring everyone back.</p>'):`<div class="next-round">${state.round>=state.settings.rounds?'Final results':'Next category'} in <b data-countdown></b>…</div>`}</section>`;
}
function render(){
  const focus=document.activeElement,id=focus?.id,selection=focus?.selectionStart;
  app.innerHTML=`<section class="room-heading"><div><span class="eyebrow">${state.phase==='lobby'?'THE PRE-PARTY':`ROUND ${state.round} OF ${state.settings.rounds}`}</span><h1>${state.phase==='lobby'?'Your crew. Your rules.':state.phase==='finished'?'Good game, great company.':'Think fast. Stay in.'}</h1></div><div class="room-actions"><button id="invite" class="room-code" title="Copy invite link"><small>ROOM CODE · COPY INVITE</small><b>${esc(state.code)} <span>↗</span></b></button><button id="leave" class="text-button">Leave room</button></div></section><div class="room-layout">${players()}<div class="main-stage">${state.phase==='lobby'?settings():board()}</div></div><div class="event-banner ${state.event?.kind==='out'?'out':''}" role="status">${!['result','finished'].includes(state.phase)?esc(state.event?.text||''):''}</div>`;
  $('#invite').onclick=async()=>{const link=new URL(`?room=${state.code}`,location.href).href;try{await navigator.clipboard.writeText(link);toast('Invite copied. Send it to your crew!');}catch{toast(`Share this room code: ${state.code}`);}};
  $('#leave').onclick=async()=>{try{await api('leave');source?.close();session=null;state=null;signature='';storage.remove('categories.session');location.href='./';}catch(error){toast(error.message);}};
  const form=$('#settings-form');if(form&&state.host===state.you){
    const read=()=>{const data=new FormData(form);return {...Object.fromEntries(data),rounds:Number(data.get('rounds')),seconds:Number(data.get('seconds')),showAnswers:data.has('showAnswers'),category:data.get('category')||'random'};};
    form.oninput=e=>{draft=read();if(e.target.name==='pack'){draft.category='random';render();}else if(e.target.name==='category')render();};
    form.onsubmit=async e=>{e.preventDefault();if(busy)return;const intent=e.submitter?.value;busy=true;const settings=read();e.submitter.disabled=true;try{await api('settings',{settings});draft=null;if(intent==='start')await api('start');else toast('Settings saved.');}catch(error){toast(error.message);}finally{busy=false;signature='';render();}};
  }
  if($('#answer-form')){
    $('#answer').oninput=e=>answerDraft=e.target.value;
    $('#answer-form').onsubmit=async e=>{e.preventDefault();if(busy)return;busy=true;const button=e.submitter;button.disabled=true;try{await api('answer',{answer:answerDraft,turn:state.turn});answerDraft='';}catch(error){toast(error.message);}finally{busy=false;if(button.isConnected)button.disabled=false;}};
  }
  if($('#callout'))$('#callout').onclick=()=>action('callout',{turn:state.turn});
  if($('#confirm-callout'))$('#confirm-callout').onclick=()=>action('confirmCallout',{turn:state.turn});
  if($('#cancel-callout'))$('#cancel-callout').onclick=()=>action('cancelCallout',{turn:state.turn});
  if($('#lobby'))$('#lobby').onclick=()=>action('lobby');
  if(id&&document.getElementById(id)){const target=document.getElementById(id);target.focus({preventScroll:true});try{target.setSelectionRange(selection,selection);}catch{}}
  else if($('#answer')&&matchMedia('(pointer:fine)').matches)$('#answer').focus({preventScroll:true});
  updateClock();
}
async function action(kind,data){if(busy)return;busy=true;try{await api(kind,data);}catch(error){toast(error.message);}finally{busy=false;}}
function updateClock(){
  if(!state)return;const now=Date.now()+offset,remaining=Math.max(0,state.deadline-now),seconds=Math.ceil(remaining/1000);
  document.querySelectorAll('[data-countdown]').forEach(el=>{el.textContent=String(seconds).padStart(2,'0');el.classList.toggle('urgent',state.phase==='turn'&&seconds<=3);});
  const undo=$('#cancel-callout');if(undo)undo.disabled=now>=state.pending.undoUntil;
  const fill=$('#timer-fill');if(fill)fill.style.transform=`scaleX(${Math.min(1,remaining/(state.settings.seconds*1000))})`;
  if(state.phase==='turn'){
    const beat=Math.max(0,Math.floor((now-state.startedAt)/500));
    document.querySelectorAll('.beats i').forEach((el,i)=>el.classList.toggle('lit',i===beat%4));
    if(beat!==lastBeat){lastBeat=beat;if(state.settings.mode==='rhythm')beep(beat%4===0?640:380,.04);else if(seconds<=3&&beat%2===0)beep(800,.06);}
  }
}
setInterval(updateClock,60);
setInterval(()=>{if(session&&Date.now()-lastMessage>7000)recover();},2000);
document.addEventListener('visibilitychange',()=>{if(!document.hidden&&session)recover();});window.addEventListener('online',recover);
try{const response=await fetch('./config');if(!response.ok)throw Error();config=await response.json();}catch{toast('Couldn’t load category options. Refresh to try again.');}
if(session){landing();await recover();}else landing();
